documentation/getting_started.md

Few small tweaks to GCP getting started
@rbuskens

Minor improvements to GCP getting started

---

documentation/ami_table.md
documentation/getting_started.md

updated ami id with public image

---

online_docs/quick_ref/ami_table.md

fixed table to correct md table format

fixed ami id table

---

documentation/properties.md

Add detailed document about Spinnaker property settings, use cases for making overrides, and background on how they leverage Spring Boot.

Properties

---

documentation/getting_started.md

I had some trouble with the naming conventions taking the "happy path" of spinnaker setup on AWS, I'm hoping these notes will help others avoid some of the time-sinks I ran in to.

Updating the setup docs

---

documentation/getting_started.md

Made some tweaks to the wording so it's less of a mouthful.
@skim1420 please review.

Tweak wording.

---

documentation/getting_started.md

Simpler getting started

---

documentation/getting_started.md

Reverts spinnaker/spinnaker.github.io#56 so open comment can be addressed.

Revert "Simpler getting started"

---

documentation/getting_started.md

@duftler @rbuskens resubmitting

Simplified getting started, fix page structure

---

documentation/troubleshooting.md

Add first item to troubleshooting guide.

---

documentation/getting_started.md

In particular the bit about adding the credentials file to the AWS instance was misleading.

added some extra detail that I found not 100% obvious in the AWS instructions

---

documentation/troubleshooting.md

Add re-configuration item to troubleshooting guide.

---

documentation/troubleshooting.md

More troubleshooting.

---

documentation/troubleshooting.md

Add additional troubleshooting entry.

---

documentation/troubleshooting.md

use h2 tags for headings to get them into side nav

---

documentation/troubleshooting.md

link to modified configuration section in troubleshooting guide

---

_includes/navigation.html
less/spinnaker-site.less
search.html

Add site search capabilities.

---

documentation/source-to-prod-codelab.md

Codelab attribution

---

documentation/configuration.md
documentation/getting_started.md
documentation/properties.md

Added configuration guide.

---

documentation/source-to-prod-codelab.md

@duftler Haven't seen this fully rendered in jekyll, but a small fix.

Fixes typo for <username>

---

documentation/source-to-prod-codelab.md

Changes "<username>" to be "codelab"

---

README.md
documentation/user_guide.md
online_docs/overview/overview.md

----
It looks like somebody else fixed a bunch of the "space between the header" just a little bit earlier, so this has less changes to it.
viewed locally

Documentation fixes
